version: 0.2

phases:
  install:
    commands:
      - echo Installing Node 14..
      - yarn install -y nodejs
      - echo Installing Yarn..
      - yarn install --no-install-recommends yarn
  pre_build:
    commands:
      - echo Installing root dependencies
      - yarn install
      - echo Installing frontend dependencies
      - yarn --cwd mern-demo-crud-app-frontend install
      - yarn --cwd mern-demo-crud-app-backend install
  build:
    commands:
      - echo Building...
      - yarn --cwd mern-demo-crud-app-frontend run build
      - yarn --cwd mern-demo-crud-app-frontend npm start
  post_build:
    commands:
      - yarn --cwd mern-demo-crud-app-backend npm start
artifacts:
  files:
    - '**/*'
    - package.json
  discard-paths: yes
  base-directory: mern-demo-crud-app-frontend/build
