version: 0.2
phases:
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install joi
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the dist folder
      - npm run build
  post_build:
    commands:
      - echo Build completed on `date`
